// ExerciseLibrary.swift
// ProjectApex — Models
//
// Canonical exercise library — single source of truth for exercise identity.
//
// All exercise_id strings written to set_logs and generated by the LLM must
// reference entries in this library. The LLM is constrained to these IDs via
// ExerciseLibrary.promptReferenceBlock() which is appended to system prompts
// at runtime in SessionPlanService, ProgramGenerationService, and
// ExerciseSwapService.
//
// ADDING EXERCISES:
//   1. Add an entry to ExerciseLibrary.all below.
//   2. The byId dictionary and promptReferenceBlock() update automatically.
//   3. If you're retiring an old freeform ID, add a normalizationMap entry.
//   4. Update backfill_primary_muscle.mjs to match.
//
// ISOLATION NOTE: nonisolated (target: SWIFT_DEFAULT_ACTOR_ISOLATION = MainActor).

import Foundation

// MARK: - ExerciseDefinition

/// A canonical exercise entry.
///
/// - `id`: Snake_case identifier, locked. Never changed once released. The LLM
///   must emit this exact string in exercise_id fields.
/// - `primaryMuscle`: PrimaryMuscle case (one of the 9 fine-grained values
///   per ADR-0005's two-level muscle taxonomy). Writers to
///   set_logs.primary_muscle pass `primaryMuscle.rawValue`.
/// - `synergists`: Free-form muscle hint strings — broader vocabulary than
///   PrimaryMuscle (e.g. "forearms" appears as a synergist on bicep curls
///   but isn't a first-class trainee-model muscle group). Stays String to
///   preserve the broader vocabulary.
/// - `movementPattern`: MovementPattern case (one of the 8 values per
///   ADR-0005). Writers to persisted fields pass `movementPattern.rawValue`.
/// - `equipmentType`: Must match an EquipmentType.typeKey from GymProfile.swift.
nonisolated struct ExerciseDefinition: Sendable, Identifiable {
    let id: String
    let name: String
    let primaryMuscle: PrimaryMuscle
    let synergists: [String]
    let movementPattern: MovementPattern
    let equipmentType: String
    let bodyweightOnly: Bool
}

// MARK: - ExerciseLibrary

/// Canonical exercise library namespace.
///
/// Usage:
///   ExerciseLibrary.lookup("barbell_bench_press")   // → ExerciseDefinition?
///   ExerciseLibrary.primaryMuscle(for: "barbell_row") // → "back"
nonisolated enum ExerciseLibrary {

    // MARK: - Full exercise list

    /// All canonical exercises. The LLM must only produce exercise_id values
    /// from this list.
    static let all: [ExerciseDefinition] = [

        // MARK: Chest
        ExerciseDefinition(
            id: "barbell_bench_press",
            name: "Barbell Bench Press",
            primaryMuscle: .chest,
            synergists: ["triceps", "shoulders"],
            movementPattern: .horizontalPush,
            equipmentType: "barbell",
            bodyweightOnly: false
        ),
        ExerciseDefinition(
            id: "dumbbell_bench_press",
            name: "Dumbbell Bench Press",
            primaryMuscle: .chest,
            synergists: ["triceps", "shoulders"],
            movementPattern: .horizontalPush,
            equipmentType: "dumbbell_set",
            bodyweightOnly: false
        ),
        ExerciseDefinition(
            id: "incline_barbell_press",
            name: "Incline Barbell Press",
            primaryMuscle: .chest,
            synergists: ["triceps", "shoulders"],
            movementPattern: .horizontalPush,
            equipmentType: "barbell",
            bodyweightOnly: false
        ),
        ExerciseDefinition(
            id: "incline_dumbbell_press",
            name: "Incline Dumbbell Press",
            primaryMuscle: .chest,
            synergists: ["triceps", "shoulders"],
            movementPattern: .horizontalPush,
            equipmentType: "dumbbell_set",
            bodyweightOnly: false
        ),
        ExerciseDefinition(
            id: "decline_bench_press",
            name: "Decline Bench Press",
            primaryMuscle: .chest,
            synergists: ["triceps", "shoulders"],
            movementPattern: .horizontalPush,
            equipmentType: "barbell",
            bodyweightOnly: false
        ),
        ExerciseDefinition(
            id: "machine_chest_press",
            name: "Machine Chest Press",
            primaryMuscle: .chest,
            synergists: ["triceps", "shoulders"],
            movementPattern: .horizontalPush,
            equipmentType: "chest_press_machine",
            bodyweightOnly: false
        ),
        ExerciseDefinition(
            id: "cable_chest_fly",
            name: "Cable Chest Fly",
            primaryMuscle: .chest,
            synergists: ["shoulders"],
            movementPattern: .isolation,
            equipmentType: "cable_crossover",
            bodyweightOnly: false
        ),
        ExerciseDefinition(
            id: "pec_deck_fly",
            name: "Pec Deck Fly",
            primaryMuscle: .chest,
            synergists: ["shoulders"],
            movementPattern: .isolation,
            equipmentType: "pec_deck",
            bodyweightOnly: false
        ),
        ExerciseDefinition(
            id: "dumbbell_fly",
            name: "Dumbbell Fly",
            primaryMuscle: .chest,
            synergists: ["shoulders"],
            movementPattern: .isolation,
            equipmentType: "dumbbell_set",
            bodyweightOnly: false
        ),
        ExerciseDefinition(
            id: "push_ups",
            name: "Push-Ups",
            primaryMuscle: .chest,
            synergists: ["triceps", "shoulders"],
            movementPattern: .horizontalPush,
            equipmentType: "flat_bench",
            bodyweightOnly: true
        ),

        // MARK: Back
        ExerciseDefinition(
            id: "barbell_row",
            name: "Barbell Row",
            primaryMuscle: .back,
            synergists: ["biceps", "shoulders"],
            movementPattern: .horizontalPull,
            equipmentType: "barbell",
            bodyweightOnly: false
        ),
        ExerciseDefinition(
            id: "dumbbell_row",
            name: "Dumbbell Row",
            primaryMuscle: .back,
            synergists: ["biceps", "shoulders"],
            movementPattern: .horizontalPull,
            equipmentType: "dumbbell_set",
            bodyweightOnly: false
        ),
        ExerciseDefinition(
            id: "t_bar_row",
            name: "T-Bar Row",
            primaryMuscle: .back,
            synergists: ["biceps", "shoulders"],
            movementPattern: .horizontalPull,
            equipmentType: "barbell",
            bodyweightOnly: false
        ),
        ExerciseDefinition(
            id: "cable_row",
            name: "Cable Row",
            primaryMuscle: .back,
            synergists: ["biceps", "shoulders"],
            movementPattern: .horizontalPull,
            equipmentType: "cable_machine_single",
            bodyweightOnly: false
        ),
        ExerciseDefinition(
            id: "seated_cable_row",
            name: "Seated Cable Row",
            primaryMuscle: .back,
            synergists: ["biceps", "shoulders"],
            movementPattern: .horizontalPull,
            equipmentType: "seated_row",
            bodyweightOnly: false
        ),
        ExerciseDefinition(
            id: "lat_pulldown_wide",
            name: "Lat Pulldown (Wide Grip)",
            primaryMuscle: .back,
            synergists: ["biceps", "shoulders"],
            movementPattern: .verticalPull,
            equipmentType: "lat_pulldown",
            bodyweightOnly: false
        ),
        ExerciseDefinition(
            id: "lat_pulldown_close",
            name: "Lat Pulldown (Close Grip)",
            primaryMuscle: .back,
            synergists: ["biceps"],
            movementPattern: .verticalPull,
            equipmentType: "lat_pulldown",
            bodyweightOnly: false
        ),
        ExerciseDefinition(
            id: "pull_ups",
            name: "Pull-Ups",
            primaryMuscle: .back,
            synergists: ["biceps"],
            movementPattern: .verticalPull,
            equipmentType: "pull_up_bar",
            bodyweightOnly: true
        ),
        ExerciseDefinition(
            id: "chin_ups",
            name: "Chin-Ups",
            primaryMuscle: .back,
            synergists: ["biceps"],
            movementPattern: .verticalPull,
            equipmentType: "pull_up_bar",
            bodyweightOnly: true
        ),
        ExerciseDefinition(
            id: "face_pull",
            name: "Face Pull",
            primaryMuscle: .back,
            synergists: ["shoulders"],
            movementPattern: .horizontalPull,
            equipmentType: "cable_machine_single",
            bodyweightOnly: false
        ),
        ExerciseDefinition(
            id: "cable_rear_delt_fly",
            name: "Cable Rear Delt Fly",
            primaryMuscle: .back,
            synergists: ["shoulders"],
            movementPattern: .isolation,
            equipmentType: "cable_crossover",
            bodyweightOnly: false
        ),
        ExerciseDefinition(
            id: "cable_straight_arm_pulldown",
            name: "Cable Straight Arm Pulldown",
            primaryMuscle: .back,
            synergists: ["triceps"],
            movementPattern: .verticalPull,
            equipmentType: "cable_machine_single",
            bodyweightOnly: false
        ),
        ExerciseDefinition(
            id: "dumbbell_single_arm_row",
            name: "Dumbbell Single Arm Row",
            primaryMuscle: .back,
            synergists: ["biceps", "shoulders"],
            movementPattern: .horizontalPull,
            equipmentType: "dumbbell_set",
            bodyweightOnly: false
        ),
        ExerciseDefinition(
            id: "assisted_pull_up",
            name: "Assisted Pull-Up",
            primaryMuscle: .back,
            synergists: ["biceps"],
            movementPattern: .verticalPull,
            // Uses the machine's weight stack for assistance — bodyweightOnly: false
            // (contrast with pull_ups which is bodyweightOnly: true).
            // equipmentType uses pull_up_bar since there is no distinct
            // assisted_pull_up_machine EquipmentType case.
            equipmentType: "pull_up_bar",
            bodyweightOnly: false
        ),

        // MARK: Shoulders
        ExerciseDefinition(
            id: "overhead_press",
            name: "Overhead Press",
            primaryMuscle: .shoulders,
            synergists: ["triceps"],
            movementPattern: .verticalPush,
            equipmentType: "barbell",
            bodyweightOnly: false
        ),
        ExerciseDefinition(
            id: "dumbbell_shoulder_press",
            name: "Dumbbell Shoulder Press",
            primaryMuscle: .shoulders,
            synergists: ["triceps"],
            movementPattern: .verticalPush,
            equipmentType: "dumbbell_set",
            bodyweightOnly: false
        ),
        ExerciseDefinition(
            id: "machine_shoulder_press",
            name: "Machine Shoulder Press",
            primaryMuscle: .shoulders,
            synergists: ["triceps"],
            movementPattern: .verticalPush,
            equipmentType: "shoulder_press_machine",
            bodyweightOnly: false
        ),
        ExerciseDefinition(
            id: "lateral_raise",
            name: "Lateral Raise",
            primaryMuscle: .shoulders,
            synergists: [],
            movementPattern: .isolation,
            equipmentType: "dumbbell_set",
            bodyweightOnly: false
        ),
        ExerciseDefinition(
            id: "cable_lateral_raise",
            name: "Cable Lateral Raise",
            primaryMuscle: .shoulders,
            synergists: [],
            movementPattern: .isolation,
            equipmentType: "cable_machine_single",
            bodyweightOnly: false
        ),
        ExerciseDefinition(
            id: "rear_delt_fly",
            name: "Rear Delt Fly",
            primaryMuscle: .shoulders,
            synergists: ["back"],
            movementPattern: .isolation,
            equipmentType: "dumbbell_set",
            bodyweightOnly: false
        ),
        ExerciseDefinition(
            id: "arnold_press",
            name: "Arnold Press",
            primaryMuscle: .shoulders,
            synergists: ["triceps"],
            movementPattern: .verticalPush,
            equipmentType: "dumbbell_set",
            bodyweightOnly: false
        ),
        ExerciseDefinition(
            id: "upright_row",
            name: "Upright Row",
            primaryMuscle: .shoulders,
            synergists: ["biceps", "back"],
            movementPattern: .verticalPull,
            equipmentType: "barbell",
            bodyweightOnly: false
        ),

        // MARK: Quads
        ExerciseDefinition(
            id: "barbell_back_squat",
            name: "Barbell Back Squat",
            primaryMuscle: .quads,
            synergists: ["glutes", "hamstrings"],
            movementPattern: .squat,
            equipmentType: "power_rack",
            bodyweightOnly: false
        ),
        ExerciseDefinition(
            id: "front_squat",
            name: "Front Squat",
            primaryMuscle: .quads,
            synergists: ["glutes", "hamstrings"],
            movementPattern: .squat,
            equipmentType: "power_rack",
            bodyweightOnly: false
        ),
        ExerciseDefinition(
            id: "leg_press",
            name: "Leg Press",
            primaryMuscle: .quads,
            synergists: ["glutes", "hamstrings"],
            movementPattern: .squat,
            equipmentType: "leg_press",
            bodyweightOnly: false
        ),
        ExerciseDefinition(
            id: "hack_squat_machine",
            name: "Hack Squat Machine",
            primaryMuscle: .quads,
            synergists: ["glutes", "hamstrings"],
            movementPattern: .squat,
            equipmentType: "hack_squat",
            bodyweightOnly: false
        ),
        ExerciseDefinition(
            id: "goblet_squat",
            name: "Goblet Squat",
            primaryMuscle: .quads,
            synergists: ["glutes"],
            movementPattern: .squat,
            equipmentType: "dumbbell_set",
            bodyweightOnly: false
        ),
        ExerciseDefinition(
            id: "leg_extension",
            name: "Leg Extension",
            primaryMuscle: .quads,
            synergists: [],
            movementPattern: .isolation,
            equipmentType: "leg_extension",
            bodyweightOnly: false
        ),
        ExerciseDefinition(
            id: "bulgarian_split_squat",
            name: "Bulgarian Split Squat",
            primaryMuscle: .quads,
            synergists: ["glutes", "hamstrings"],
            movementPattern: .lunge,
            equipmentType: "dumbbell_set",
            bodyweightOnly: false
        ),
        ExerciseDefinition(
            id: "walking_lunge",
            name: "Walking Lunge",
            primaryMuscle: .quads,
            synergists: ["glutes", "hamstrings"],
            movementPattern: .lunge,
            equipmentType: "dumbbell_set",
            bodyweightOnly: false
        ),
        ExerciseDefinition(
            id: "smith_machine_squat",
            name: "Smith Machine Squat",
            primaryMuscle: .quads,
            synergists: ["glutes", "hamstrings"],
            movementPattern: .squat,
            equipmentType: "smith_machine",
            bodyweightOnly: false
        ),

        // MARK: Hamstrings
        ExerciseDefinition(
            id: "conventional_deadlift",
            name: "Conventional Deadlift",
            primaryMuscle: .hamstrings,
            synergists: ["glutes", "back"],
            movementPattern: .hipHinge,
            equipmentType: "barbell",
            bodyweightOnly: false
        ),
        ExerciseDefinition(
            id: "romanian_deadlift",
            name: "Romanian Deadlift",
            primaryMuscle: .hamstrings,
            synergists: ["glutes"],
            movementPattern: .hipHinge,
            equipmentType: "barbell",
            bodyweightOnly: false
        ),
        ExerciseDefinition(
            id: "dumbbell_romanian_deadlift",
            name: "Dumbbell Romanian Deadlift",
            primaryMuscle: .hamstrings,
            synergists: ["glutes"],
            movementPattern: .hipHinge,
            equipmentType: "dumbbell_set",
            bodyweightOnly: false
        ),
        ExerciseDefinition(
            id: "lying_leg_curl",
            name: "Lying Leg Curl",
            primaryMuscle: .hamstrings,
            synergists: [],
            movementPattern: .isolation,
            equipmentType: "leg_curl",
            bodyweightOnly: false
        ),
        ExerciseDefinition(
            id: "seated_leg_curl",
            name: "Seated Leg Curl",
            primaryMuscle: .hamstrings,
            synergists: [],
            movementPattern: .isolation,
            equipmentType: "leg_curl",
            bodyweightOnly: false
        ),
        ExerciseDefinition(
            id: "stiff_leg_deadlift",
            name: "Stiff Leg Deadlift",
            primaryMuscle: .hamstrings,
            synergists: ["glutes", "back"],
            movementPattern: .hipHinge,
            equipmentType: "barbell",
            bodyweightOnly: false
        ),

        // MARK: Glutes
        ExerciseDefinition(
            id: "hip_thrust",
            name: "Hip Thrust",
            primaryMuscle: .glutes,
            synergists: ["hamstrings"],
            movementPattern: .hipHinge,
            equipmentType: "barbell",
            bodyweightOnly: false
        ),
        ExerciseDefinition(
            id: "cable_pull_through",
            name: "Cable Pull-Through",
            primaryMuscle: .glutes,
            synergists: ["hamstrings"],
            movementPattern: .hipHinge,
            equipmentType: "cable_machine_single",
            bodyweightOnly: false
        ),
        ExerciseDefinition(
            id: "glute_bridge",
            name: "Glute Bridge",
            primaryMuscle: .glutes,
            synergists: ["hamstrings"],
            movementPattern: .hipHinge,
            equipmentType: "flat_bench",
            bodyweightOnly: true
        ),
        ExerciseDefinition(
            id: "sumo_deadlift",
            name: "Sumo Deadlift",
            primaryMuscle: .glutes,
            synergists: ["hamstrings", "quads"],
            movementPattern: .hipHinge,
            equipmentType: "barbell",
            bodyweightOnly: false
        ),

        // MARK: Biceps
        ExerciseDefinition(
            id: "barbell_curl",
            name: "Barbell Curl",
            primaryMuscle: .biceps,
            synergists: ["forearms"],
            movementPattern: .isolation,
            equipmentType: "barbell",
            bodyweightOnly: false
        ),
        ExerciseDefinition(
            id: "ez_bar_curl",
            name: "EZ Bar Curl",
            primaryMuscle: .biceps,
            synergists: ["forearms"],
            movementPattern: .isolation,
            equipmentType: "ez_curl_bar",
            bodyweightOnly: false
        ),
        ExerciseDefinition(
            id: "dumbbell_curl",
            name: "Dumbbell Curl",
            primaryMuscle: .biceps,
            synergists: ["forearms"],
            movementPattern: .isolation,
            equipmentType: "dumbbell_set",
            bodyweightOnly: false
        ),
        ExerciseDefinition(
            id: "preacher_curl",
            name: "Preacher Curl",
            primaryMuscle: .biceps,
            synergists: [],
            movementPattern: .isolation,
            equipmentType: "preacher_curl",
            bodyweightOnly: false
        ),
        ExerciseDefinition(
            id: "hammer_curl",
            name: "Hammer Curl",
            primaryMuscle: .biceps,
            synergists: ["forearms"],
            movementPattern: .isolation,
            equipmentType: "dumbbell_set",
            bodyweightOnly: false
        ),
        ExerciseDefinition(
            id: "cable_curl",
            name: "Cable Curl",
            primaryMuscle: .biceps,
            synergists: ["forearms"],
            movementPattern: .isolation,
            equipmentType: "cable_machine_single",
            bodyweightOnly: false
        ),
        ExerciseDefinition(
            id: "cable_hammer_curl",
            name: "Cable Hammer Curl",
            primaryMuscle: .biceps,
            synergists: ["forearms"],
            movementPattern: .isolation,
            equipmentType: "cable_machine_single",
            bodyweightOnly: false
        ),

        // MARK: Triceps
        ExerciseDefinition(
            id: "cable_tricep_pushdown",
            name: "Cable Tricep Pushdown",
            primaryMuscle: .triceps,
            synergists: [],
            movementPattern: .isolation,
            equipmentType: "cable_machine_single",
            bodyweightOnly: false
        ),
        ExerciseDefinition(
            id: "overhead_tricep_extension",
            name: "Overhead Tricep Extension",
            primaryMuscle: .triceps,
            synergists: [],
            movementPattern: .isolation,
            equipmentType: "dumbbell_set",
            bodyweightOnly: false
        ),
        ExerciseDefinition(
            id: "skull_crushers",
            name: "Skull Crushers",
            primaryMuscle: .triceps,
            synergists: [],
            movementPattern: .isolation,
            equipmentType: "ez_curl_bar",
            bodyweightOnly: false
        ),
        ExerciseDefinition(
            id: "dips",
            name: "Dips",
            primaryMuscle: .triceps,
            synergists: ["chest", "shoulders"],
            movementPattern: .verticalPush,
            equipmentType: "dip_station",
            bodyweightOnly: true
        ),
        ExerciseDefinition(
            id: "close_grip_bench_press",
            name: "Close Grip Bench Press",
            primaryMuscle: .triceps,
            synergists: ["chest", "shoulders"],
            movementPattern: .horizontalPush,
            equipmentType: "barbell",
            bodyweightOnly: false
        ),
        ExerciseDefinition(
            id: "dumbbell_overhead_tricep_extension",
            name: "Dumbbell Overhead Tricep Extension",
            primaryMuscle: .triceps,
            synergists: [],
            movementPattern: .isolation,
            equipmentType: "dumbbell_set",
            bodyweightOnly: false
        ),
        ExerciseDefinition(
            id: "cable_overhead_tricep_extension",
            name: "Cable Overhead Tricep Extension",
            primaryMuscle: .triceps,
            synergists: [],
            movementPattern: .isolation,
            equipmentType: "cable_machine_single",
            bodyweightOnly: false
        ),

        // MARK: Chest (Smith machine variants)
        ExerciseDefinition(
            id: "smith_machine_bench_press",
            name: "Smith Machine Bench Press",
            primaryMuscle: .chest,
            synergists: ["triceps", "shoulders"],
            movementPattern: .horizontalPush,
            equipmentType: "smith_machine",
            bodyweightOnly: false
        ),
        ExerciseDefinition(
            id: "smith_machine_incline_press",
            name: "Smith Machine Incline Press",
            primaryMuscle: .chest,
            synergists: ["triceps", "shoulders"],
            movementPattern: .horizontalPush,
            equipmentType: "smith_machine",
            bodyweightOnly: false
        ),
        ExerciseDefinition(
            id: "cable_crossover_chest_fly",
            name: "Cable Crossover Chest Fly",
            primaryMuscle: .chest,
            synergists: ["shoulders"],
            movementPattern: .isolation,
            equipmentType: "cable_crossover",
            bodyweightOnly: false
        ),

        // MARK: Calves
        ExerciseDefinition(
            id: "standing_calf_raise",
            name: "Standing Calf Raise",
            primaryMuscle: .calves,
            synergists: [],
            movementPattern: .isolation,
            equipmentType: "barbell",
            bodyweightOnly: false
        ),
        ExerciseDefinition(
            id: "seated_calf_raise",
            name: "Seated Calf Raise",
            primaryMuscle: .calves,
            synergists: [],
            movementPattern: .isolation,
            equipmentType: "leg_press",
            bodyweightOnly: false
        ),
        ExerciseDefinition(
            id: "smith_machine_calf_raise",
            name: "Smith Machine Calf Raise",
            primaryMuscle: .calves,
            synergists: [],
            movementPattern: .isolation,
            equipmentType: "smith_machine",
            bodyweightOnly: false
        ),

        // Core exercises (cable_crunch, hanging_leg_raise, ab_wheel_rollout,
        // plank) were removed in Phase 1 / Slice 1. Per ADR-0005's two-level
        // muscle taxonomy, core is excluded from both PrimaryMuscle and
        // MuscleGroup — core training stimuli don't fit the EWMA-over-top-sets
        // model and the trainee model has no axis to track core capability.
    ]

    // MARK: - Lookup infrastructure

    /// O(1) lookup by canonical exercise_id.
    static let byId: [String: ExerciseDefinition] = {
        Dictionary(uniqueKeysWithValues: all.map { ($0.id, $0) })
    }()

    /// Returns the canonical definition for an exercise_id.
    ///
    /// Resolution order:
    ///   1. Direct match in `byId`
    ///   2. Normalization map → byId
    ///   3. nil — unknown exercise
    static func lookup(_ exerciseId: String) -> ExerciseDefinition? {
        if let direct = byId[exerciseId] { return direct }
        if let canonical = normalizationMap[exerciseId] { return byId[canonical] }
        return nil
    }

    /// Returns the typed PrimaryMuscle for a given exercise_id. Callers
    /// writing the primary_muscle column in set_logs payloads pass
    /// `.rawValue` to convert at the persistence boundary.
    static func primaryMuscle(for exerciseId: String) -> PrimaryMuscle? {
        lookup(exerciseId)?.primaryMuscle
    }

    // MARK: - Normalization map
    //
    // Maps known historical LLM-generated variant strings to their canonical IDs.
    //
    // BEFORE RUNNING backfill_primary_muscle.mjs:
    // Dump the distinct exercise_id values from set_logs and review these mappings
    // against actual data. A wrong mapping here corrupts historical lift data.
    //
    // Keys in this map must NOT exist as canonical IDs in `all`.
    // Values must all be valid canonical IDs present in `byId`.
    // The unit test "normalizationMap values all point to valid canonical IDs"
    // will catch any errors here.
    static let normalizationMap: [String: String] = [
        // Bench press variants
        "bench_press":              "barbell_bench_press",
        "flat_bench_press":         "barbell_bench_press",
        "bb_bench_press":           "barbell_bench_press",
        "db_bench_press":           "dumbbell_bench_press",
        "incline_press":            "incline_dumbbell_press",
        "incline_db_press":         "incline_dumbbell_press",

        // Row variants
        "bent_over_row":            "barbell_row",
        "bent_over_barbell_row":    "barbell_row",
        "bb_row":                   "barbell_row",
        "barbell_bent_over_row":    "barbell_row",
        "db_row":                   "dumbbell_row",
        "one_arm_dumbbell_row":     "dumbbell_row",

        // Lat pulldown variants — only mapping the clearly wrong spelling.
        // "lat_pulldown" (no suffix) is intentionally NOT mapped here because
        // it is ambiguous between lat_pulldown_wide and lat_pulldown_close.
        // It will appear as unresolved in the backfill output for human review.
        "lat_pull_down":            "lat_pulldown_wide",
        "lat_pulldown_overhand":    "lat_pulldown_wide",

        // Pull-up / chin-up variants
        "pull_up":                  "pull_ups",
        "pullup":                   "pull_ups",
        "pull-up":                  "pull_ups",
        "chin_up":                  "chin_ups",
        "chinup":                   "chin_ups",

        // Squat variants
        "back_squat":               "barbell_back_squat",
        "squat":                    "barbell_back_squat",
        "barbell_squat":            "barbell_back_squat",
        "low_bar_squat":            "barbell_back_squat",

        // Deadlift variants
        "deadlift":                 "conventional_deadlift",
        "barbell_deadlift":         "conventional_deadlift",
        "rdl":                      "romanian_deadlift",
        "barbell_rdl":              "romanian_deadlift",
        "barbell_romanian_deadlift": "romanian_deadlift",
        "stiff_legged_deadlift":    "stiff_leg_deadlift",
        "sldl":                     "stiff_leg_deadlift",

        // OHP variants
        "ohp":                      "overhead_press",
        "barbell_ohp":              "overhead_press",
        "barbell_overhead_press":   "overhead_press",
        "military_press":           "overhead_press",
        "db_shoulder_press":        "dumbbell_shoulder_press",
        "seated_dumbbell_press":    "dumbbell_shoulder_press",

        // Curl variants
        "bicep_curl":               "dumbbell_curl",
        "biceps_curl":              "dumbbell_curl",
        "db_curl":                  "dumbbell_curl",
        "barbell_bicep_curl":       "barbell_curl",
        "ez_curl":                  "ez_bar_curl",

        // Tricep variants
        "tricep_pushdown":          "cable_tricep_pushdown",
        "triceps_pushdown":         "cable_tricep_pushdown",
        "rope_pushdown":            "cable_tricep_pushdown",
        "overhead_extension":       "overhead_tricep_extension",
        "db_overhead_extension":    "overhead_tricep_extension",
        "lying_tricep_extension":   "skull_crushers",

        // Lat pulldown — grip-specific variants seen in live data
        "cable_pulldown_neutral_grip": "lat_pulldown_close",
        "lat_pulldown_wide_grip":    "lat_pulldown_wide",

        // Dumbbell press variants seen in live data
        "dumbbell_flat_press":      "dumbbell_bench_press",
        "dumbbell_incline_press":   "incline_dumbbell_press",

        // Curl/raise variants seen in live data
        "dumbbell_bicep_curl":      "dumbbell_curl",
        "dumbbell_lateral_raise":   "lateral_raise",

        // Misc
        "split_squat":              "bulgarian_split_squat",
        "lunge":                    "walking_lunge",
        "leg_curl":                 "lying_leg_curl",
        "hamstring_curl":           "lying_leg_curl",
        "calf_raise":               "standing_calf_raise",
        "barbell_hip_thrust":       "hip_thrust",
        "glute_hip_thrust":         "hip_thrust",
        "lateral_raises":           "lateral_raise",
        "side_lateral_raise":       "lateral_raise",
        "reverse_fly":              "rear_delt_fly",
        "rear_delt_raise":          "rear_delt_fly",
    ]

    // MARK: - Prompt reference block

    /// Generates the canonical exercise reference block appended to LLM system prompts.
    ///
    /// Produces a pipe-delimited table (~320 tokens) listing all exercises the
    /// LLM is permitted to prescribe. Called at runtime by:
    ///   - SessionPlanService.loadSystemPrompt()
    ///   - ProgramGenerationService.loadSystemPrompt()
    ///   - ExerciseSwapService.systemPrompt (static initialiser)
    static func promptReferenceBlock() -> String {
        let separator = String(repeating: "═", count: 63)
        var lines: [String] = [
            "",
            separator,
            "CANONICAL EXERCISE LIBRARY",
            separator,
            "You MUST only prescribe exercises from this list.",
            "Use the exact exercise_id string — never invent new IDs.",
            "If no exercise in the list fits the required movement and equipment,",
            "select the closest match.",
            "",
            "exercise_id | name | primary_muscle | equipment_required",
        ]

        // Group by primaryMuscle for readability in the prompt. Order
        // matches the prior chest→back→shoulders→…→calves layout (core is
        // intentionally excluded — the 4 core exercises were removed in
        // Phase 1 / Slice 1).
        let grouped = Dictionary(grouping: all, by: \.primaryMuscle)
        let muscleOrder: [PrimaryMuscle] = [
            .chest, .back, .shoulders,
            .quads, .hamstrings, .glutes,
            .biceps, .triceps, .calves,
        ]
        for muscle in muscleOrder {
            guard let exercises = grouped[muscle] else { continue }
            for ex in exercises.sorted(by: { $0.id < $1.id }) {
                lines.append("\(ex.id) | \(ex.name) | \(ex.primaryMuscle.rawValue) | \(ex.equipmentType)")
            }
        }

        lines.append(separator)
        return lines.joined(separator: "\n")
    }
}
